### ISSUE TITLE
Crash on Fabric Server 1.19.3

### ISSUE THREAD

**Issue by Cethien** [Skidamek/AutoModpack#80]
**Describe the bug**
I have a server on 1.19.2 which works completly fine. I created a Test Instance with 1.19.3 in Docker, which crashes. Right now I have a setup of only fabric API and AutoModpack. Still crashes

**To Reproduce**
1. Create Docker-Compose
2. docker compose up
3. crash

**Expected behavior**
server starting

**Screenshots**

**AutoModpack and Minecraft Version you are using (please complete the following information):**
 - Minecraft 1.19.3
 - Fabric Server - loader 0.14.11 - launcher 0.11.1
 - AutoModpack 2.4.1

**Additional context**
I manage my mods with a unused instance in Prism.

here is my docker-compose if helpful:
```docker
version: '3.4'

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 24891:25565
    environment:
      - EULA=TRUE
      - TYPE=FABRIC
      - VERSION=1.19.3
    tty: true
    stdin_open: true
    volumes:
      - ./server-data:/data
      - ./server-data/logs:/data/logs
      - ./.minecraft/world/datapacks:/data/world/datapacks
      - ./.minecraft/mods:/data/mods
      - ./.minecraft/config:/data/config
```

**Server log**
```log
[21:23:04] [main/INFO]: Loading Minecraft 1.19.3 with Fabric Loader 0.14.11
[21:23:05] [main/INFO]: Loading 41 mods:
	- automodpack 2.4.1
	- fabric-api 0.69.1+1.19.3
	- fabric-api-base 0.4.19+8d1895cf85 via fabric-api
	- fabric-api-lookup-api-v1 1.6.18+49abcf7e85 via fabric-api
	- fabric-biome-api-v1 12.0.0+689f5e7185 via fabric-api
	- fabric-block-api-v1 1.0.3+12bfe4ea85 via fabric-api
	- fabric-command-api-v1 1.2.19+f71b366f85 via fabric-api
	- fabric-command-api-v2 2.1.15+49abcf7e85 via fabric-api
	- fabric-commands-v0 0.2.36+df3654b385 via fabric-api
	- fabric-containers-v0 0.1.44+df3654b385 via fabric-api
	- fabric-content-registries-v0 3.4.12+49abcf7e85 via fabric-api
	- fabric-convention-tags-v1 1.2.0+8e4e694f85 via fabric-api
	- fabric-crash-report-info-v1 0.2.12+aeb40ebe85 via fabric-api
	- fabric-data-generation-api-v1 11.1.1+112a38be85 via fabric-api
	- fabric-dimensions-v1 2.1.39+48349a3f85 via fabric-api
	- fabric-entity-events-v1 1.5.5+b83334a085 via fabric-api
	- fabric-events-interaction-v0 0.4.37+422b77fb85 via fabric-api
	- fabric-events-lifecycle-v0 0.2.39+df3654b385 via fabric-api
	- fabric-game-rule-api-v1 1.0.28+2894d6df85 via fabric-api
	- fabric-item-api-v1 2.1.5+4d2c606385 via fabric-api
	- fabric-item-group-api-v1 2.1.8+d3d735d085 via fabric-api
	- fabric-lifecycle-events-v1 2.2.8+2894d6df85 via fabric-api
	- fabric-loot-api-v2 1.1.18+75e9821185 via fabric-api
	- fabric-loot-tables-v1 1.1.22+9e7660c685 via fabric-api
	- fabric-message-api-v1 5.0.12+6ede1da985 via fabric-api
	- fabric-mining-level-api-v1 2.1.29+49abcf7e85 via fabric-api
	- fabric-networking-api-v1 1.2.14+d9ac3c3985 via fabric-api
	- fabric-networking-v0 0.3.31+df3654b385 via fabric-api
	- fabric-object-builder-api-v1 5.2.0+e9dee00485 via fabric-api
	- fabric-particles-v1 1.0.18+fbde993d85 via fabric-api
	- fabric-registry-sync-v0 2.0.1+2608564685 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.23+48349a3f85 via fabric-api
	- fabric-rendering-fluids-v1 3.0.16+3067f46385 via fabric-api
	- fabric-resource-conditions-api-v1 2.2.0+280be3ab85 via fabric-api
	- fabric-resource-loader-v0 0.10.3+a10d22bd85 via fabric-api
	- fabric-screen-handler-api-v1 1.3.10+689f5e7185 via fabric-api
	- fabric-transfer-api-v1 2.1.12+82a2701785 via fabric-api
	- fabric-transitive-access-wideners-v1 2.1.0+0efcd39b85 via fabric-api
	- fabricloader 0.14.11
	- java 17
	- minecraft 1.19.3
[21:23:05] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/data/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[21:23:05] [main/INFO]: Compatibility level set to JAVA_17
[21:23:07] [main/INFO]: Prelaunching AutoModpack...
[21:23:07] [main/INFO]: Checking if AutoModpack is up-to-date...
[21:23:08] [main/ERROR]: A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'automodpack'!
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:164) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.19.3-loader.0.14.11-launcher.0.11.1.jar:0.11.1]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'automodpack'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.11.jar:?]
	... 4 more
Caused by: java.lang.NullPointerException: Cannot invoke "String.split(String)" because "pl.skidam.automodpack.utils.ModrinthAPI.modrinthAPIversion" is null
	at pl.skidam.automodpack.server.ServerSelfUpdater.<init>(ServerSelfUpdater.java:24) ~[AutoModpack-1.19.x.jar:?]
	at pl.skidam.automodpack.PreLoad.onPreLaunch(PreLoad.java:58) ~[AutoModpack-1.19.x.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.11.jar:?]
	... 4 more

```

**Comment by Skidamek** [comment]
Hello, this mod wasn't updated to 1.19.3 and i am not sure if it will work without update, however your crash was coused by modrinth exactly by my self update system which using modrinth to download mod, and there mod was set that works from 1.19 to 1.19.2. I am just added 1.19.3 and crash should be resolved.

**Comment by Cethien** [comment]
spun up the container again, seems to work. thank you

**Comment by Shadowrs** [comment]
this still happens to me - i downloaded AutoModpack-1.19.x from modrinth- any other way to fix?

**Comment by Skidamek** [comment]
> this still happens to me - i downloaded AutoModpack-1.19.x from modrinth- any other way to fix?

Sorry no fix yet, removed 1.19.3 from supported versions due to issues in #81

**Comment by Skidamek** [comment]
> this still happens to me - i downloaded AutoModpack-1.19.x from modrinth- any other way to fix?

Added support to 1.19.3 in 3.0.1 :)
