### ISSUE TITLE
Errors while downloading modpack

### ISSUE THREAD

**Issue by dAKirby309** [Skidamek/AutoModpack#92]
Firstly is there a way to prevent the system from updating itself? Because it was working great before until it updated itself to the new version (3.0.1) and then things broke. 

I'm on Minecraft 1.19.0 Fabric. The Automodpack jar version I had (v2.4.1) on my client and server is no longer recognized as a mod, and this newest 3.0.1 version that it installed or even when I installed it manually makes the mod "seen" in my list of mods on client, but none of its functionality works. No check for update button, no auto-syncing with our server, nothing. 

And also no mention of Automodpack doing anything in the server logs.

I don't know why or how it got messed up but this is a setback since I was needing to test other things and instead I had to spend my time trying to figure this out to no avail.

I tried updating and messing with Automodpack on my server and client. No dice.

**Comment by Inversil** [comment]
yeah this sucks, setting updateCheck to false also doesn't seem to mitigate the automatic update.

**Comment by Skidamek** [comment]
My bad, I'm thinking of removing the auto-update system. Based on the stats on modrinth, it seems like it downloads the quilt version of the mod even when you play on fabric, which could be why things aren't working for you. You can try redownloading the correct version of the mod, like fabric 1.19.2, and see if that helps.

**Comment by Skidamek** [comment]
Also modified previous jars (2.4.1) to prevent auto-updates to 3.x.x.

https://modrinth.com/mod/automodpack/version/2.4.1-1.19
https://modrinth.com/mod/automodpack/version/2.4.1-1.18

**Comment by Inversil** [comment]
thank you!! I was using the old version because it still has support for the cloud hosted modpack zip link. You didn't have to do this - but you did, so thank you so much!

**Comment by dAKirby309** [comment]
> Also modified previous jars (2.4.1) to prevent auto-updates to 3.x.x. (On modrinth and github, cf doesn't provide that option), so you can use the old version if you want to.
> 
> https://modrinth.com/mod/automodpack/version/2.4.1-1.19 https://modrinth.com/mod/automodpack/version/2.4.1-1.18

I really appreciate your quick response to this! However, I'm still getting the problem where it automatically updates to 3.01 by downloading the modified jar that you linked me for 1.19. I deleted the existing AutoModpack jars. What else am I missing here?

**Comment by Inversil** [comment]
Hello! just tested it. running into the same thing- it still updates.

**Comment by RatDonkeyGoat** [comment]
hey everyone i fixed 2.4.1 to not auto update anymore if you would like the file here you go!

https://github.com/Skidamek/AutoModpack/issues/92#issuecomment-1413678240
these files do not work 

[Old AutoModpack without auto updating.zip](https://github.com/Skidamek/AutoModpack/files/10575991/Old.AutoModpack.without.auto.updating.zip)
this above file will work

**Comment by Skidamek** [comment]
Hey, thanks @RatDonkeyGoat, i improved that a bit and updated jars again!

https://modrinth.com/mod/automodpack/version/2.4.1-1.19
https://modrinth.com/mod/automodpack/version/2.4.1-1.18

**Comment by dAKirby309** [comment]
I don't know what's going on here. Does this updated 2.4.1 jar prevent auto-updates now? Yes. Does it seem to work properly? Not that I can tell. 

Firstly, I simply downloaded this 2.4.1 jar into the /mods/ folder on client and server. Secondly, I launched the server and then deleted all of the mods in the client's /mods/ folder and then I re-ran the client and tried to connect. I got an error:
![image](https://user-images.githubusercontent.com/20955478/216759929-89792057-b989-42dc-97d3-6d488481ce65.png)

Secondly, in order to try and fix this, I deleted the existing Automodpack folder in the server and re-ran client and server. Upon simply opening the client Minecraft Launcher and pressing Play, it got a popup ever time saying to update the modpack and it did not actually launch the game and the server logs said this in the screenshot  each time. I tried 7 times. 
![image](https://user-images.githubusercontent.com/20955478/216759968-8efa0d5e-6c1d-45eb-b1b7-4ac7d062472b.png)
![image](https://user-images.githubusercontent.com/20955478/216760111-c90171d1-519d-470e-bd0b-0a2f1f69557d.png)

Next, I deleted the mods (except for Automodpack.jar) and the Automodpack folder on my client and relaunched the client by pressing Play on the Launcher and the game did launch this time and I tried to connect to the server, and it downloaded the mods. Upon restarting my client and trying to reconnect to the server, I was greeted with yet another error screen 
![image](https://user-images.githubusercontent.com/20955478/216760166-f44cf406-c6a1-4669-864f-5f4dfd47971d.png)

And I still cannot connect to the server. 
What is going on here?!

**Comment by Skidamek** [comment]
Thats old automodpack bug from 2.4.1 look #69 
This is fixed in v3

But to bypass it you should be able to just delete AutoModpack folder on client restart game, join server, download modpack again and it should work again

**Comment by dAKirby309** [comment]
Like I mentioned, I already tried this. But I tried it again now, and the same thing happens.

![image](https://user-images.githubusercontent.com/20955478/216762898-c8c89784-72d2-437e-92ee-c6604922871a.png)
![image](https://user-images.githubusercontent.com/20955478/216762940-397c09aa-914c-4a41-8715-ef21df824301.png)

**Comment by Skidamek** [comment]
I see, so looks like this isn't automodpack releated bug or that's old 2.4.1 version bug which is already fixed in new 3.0.1 version

**Comment by Skidamek** [comment]
Better try new version...
https://modrinth.com/mod/automodpack/version/uodQ7wS5

**Comment by dAKirby309** [comment]
![image](https://user-images.githubusercontent.com/20955478/216764183-00e7f708-200f-4a1a-9990-c4b7eb521799.png)
![image](https://user-images.githubusercontent.com/20955478/216764189-7abd8e7b-3540-4033-b9b2-486f6ec8acd2.png)
Then I press restart, and then I relaunch the game and nothing happens.

On the server side, I removed the existing Automodpack folder to let it regenerate with 3.0.1 and these are the only files it produces when launching the server:
![image](https://user-images.githubusercontent.com/20955478/216764444-7c0d0c03-e197-45b5-a669-89b692548f5c.png)

**Comment by dAKirby309** [comment]
Ok so I downloaded your Automodpack 3.0.1.jar on client and server and did the following...

I deleted the existing automodpack folder on client and on server, and I deleted the config for both of them so that all the automodpack files could regenerate.
Note: the automodpack config file did not regenerate on my client when launching the game or anything, so I restored the config file from the recycle bin. But doing so makes no difference to the end-result. 

Only the automodpack.jar is in /mods/ and it installs fabric api like it should. 
![image](https://user-images.githubusercontent.com/20955478/216764940-3f3206c9-8022-43cf-addd-47bd910d42c6.png)
![image](https://user-images.githubusercontent.com/20955478/216765097-84976040-b521-41fb-8ccf-49c5339bc1e5.png)

Then I relaunch Fabric 1.19 client and join the server, and it downloads the mods
![image](https://user-images.githubusercontent.com/20955478/216765017-a8a1caca-8591-4736-adc0-9e83992edba6.png)

I click on Restart on the client
![image](https://user-images.githubusercontent.com/20955478/216765028-749b87ba-5287-447e-beb0-2d146eef7b5f.png)

Fabric API gets deleted on its own
![image](https://user-images.githubusercontent.com/20955478/216765057-00d96f0e-7c3e-427e-b22e-758ed29153f5.png)

I relaunch the game from client again, and nothing happens. The game does not then launch. I've tried going through this multiple times.

And even if I manually put Fabric API.jar into the /mods/ folder, it gets deleted on its own when I try launching the game. No other mods from the server go into the /mods/ folder like they're supposed to.

This is not working.

**Comment by dAKirby309** [comment]
(Sorry for the ghost posts that I deleted. Both times, I accidentally commented too early)
Ok so I downloaded your Automodpack 3.0.1.jar on client and server and did the following...

I deleted the existing automodpack folder on client and on server, and I deleted the config for both of them so that all the automodpack files could regenerate.
Note: the automodpack config file did not regenerate on my client when launching the game or anything, so I restored the config file from the recycle bin. But doing so makes no difference to the end-result. 

Only the automodpack.jar is in /mods/ and it installs fabric api like it should. 
![image](https://user-images.githubusercontent.com/20955478/216764940-3f3206c9-8022-43cf-addd-47bd910d42c6.png)
![image](https://user-images.githubusercontent.com/20955478/216765097-84976040-b521-41fb-8ccf-49c5339bc1e5.png)

Then I relaunch Fabric 1.19 client and join the server, and it downloads the mods
![image](https://user-images.githubusercontent.com/20955478/216765017-a8a1caca-8591-4736-adc0-9e83992edba6.png)

I click on Restart on the client
![image](https://user-images.githubusercontent.com/20955478/216765028-749b87ba-5287-447e-beb0-2d146eef7b5f.png)

Fabric API gets deleted on its own
![image](https://user-images.githubusercontent.com/20955478/216765524-8472d46d-87e8-4336-9049-bc05ca524730.png)

I relaunch the game from client again, and nothing happens. The game does not then launch. I've tried going through this multiple times.

And even if I manually put Fabric API.jar into the /mods/ folder, it gets deleted on its own when I try launching the game. No other mods from the server go into the /mods/ folder like they're supposed to.

This is not working.

**Comment by Skidamek** [comment]
Looks similar to #93 
Can you send last two logs from client?

**Comment by dAKirby309** [comment]
[2023-02-04-6.log.gz](https://github.com/Skidamek/AutoModpack/files/10608580/2023-02-04-6.log.gz)
[2023-02-04-7.log.gz](https://github.com/Skidamek/AutoModpack/files/10608581/2023-02-04-7.log.gz)
[latest.log](https://github.com/Skidamek/AutoModpack/files/10608582/latest.log)

**Comment by Skidamek** [comment]
Oh no, you get stuck in the loop

Can you send from server these files? (worldedit.properties, FabricHomes.properties)

[05:41:52] [pool-2-thread-4/INFO]: Downloading worldedit.properties... (attempt 1)
[05:41:52] [pool-2-thread-3/INFO]: Downloading FabricHomes.properties... (attempt 1)
[05:41:52] [pool-2-thread-4/INFO]: URL: http://192.168.86.137:30037/config/worldedit/worldedit.properties
[05:41:52] [pool-2-thread-3/INFO]: URL: http://192.168.86.137:30037/config/FabricHomes.properties
[05:41:52] [pool-2-thread-3/WARN]: Checksums do not match, retrying... client: 9376724cc233a3f5f7d5d127e6c3ee8e9b18b4016e1c898adaf73136f5f02482 server: a96d33cbcbc429a458e6d4472c14aa826f9f91e8a0b183e7c945f958c6157dab
[05:41:52] [pool-2-thread-4/WARN]: Checksums do not match, retrying... client: cd2e140e591c36a9dcef2e92a7d4864cc497fd9843d09fd0f0d5bb1d3abb699c server: 8d50898fac9cec9d83ea6e7329f7285aa370bf616f8666785a1a225052beb638
[05:41:52] [pool-2-thread-3/INFO]: Downloading FabricHomes.properties... (attempt 2)
[05:41:52] [pool-2-thread-4/INFO]: Downloading worldedit.properties... (attempt 2)
[05:41:52] [pool-2-thread-3/INFO]: URL: http://192.168.86.137:30037/config/FabricHomes.properties
[05:41:52] [pool-2-thread-4/INFO]: URL: http://192.168.86.137:30037/config/worldedit/worldedit.properties
[05:41:52] [pool-2-thread-3/WARN]: Checksums do not match, retrying... client: 9376724cc233a3f5f7d5d127e6c3ee8e9b18b4016e1c898adaf73136f5f02482 server: a96d33cbcbc429a458e6d4472c14aa826f9f91e8a0b183e7c945f958c6157dab
[05:41:52] [pool-2-thread-4/WARN]: Checksums do not match, retrying... client: cd2e140e591c36a9dcef2e92a7d4864cc497fd9843d09fd0f0d5bb1d3abb699c server: 8d50898fac9cec9d83ea6e7329f7285aa370bf616f8666785a1a225052beb638
[05:41:52] [pool-2-thread-3/INFO]: Downloading FabricHomes.properties... (attempt 3)
[05:41:52] [pool-2-thread-4/INFO]: Downloading worldedit.properties... (attempt 3)
[05:41:52] [pool-2-thread-3/INFO]: URL: http://192.168.86.137:30037/config/FabricHomes.properties
[05:41:52] [pool-2-thread-4/INFO]: URL: http://192.168.86.137:30037/config/worldedit/worldedit.properties
[05:41:52] [pool-2-thread-3/WARN]: Checksums do not match, retrying... client: 9376724cc233a3f5f7d5d127e6c3ee8e9b18b4016e1c898adaf73136f5f02482 server: a96d33cbcbc429a458e6d4472c14aa826f9f91e8a0b183e7c945f958c6157dab
[05:41:52] [pool-2-thread-4/WARN]: Checksums do not match, retrying... client: cd2e140e591c36a9dcef2e92a7d4864cc497fd9843d09fd0f0d5bb1d3abb699c server: 8d50898fac9cec9d83ea6e7329f7285aa370bf616f8666785a1a225052beb638
[05:41:52] [pool-2-thread-3/INFO]: Downloading FabricHomes.properties... (attempt 4)
[05:41:52] [pool-2-thread-3/INFO]: URL: http://192.168.86.137:30037/config/FabricHomes.properties
[05:41:52] [pool-2-thread-4/INFO]: Downloading worldedit.properties... (attempt 4)
[05:41:52] [pool-2-thread-4/INFO]: URL: http://192.168.86.137:30037/config/worldedit/worldedit.properties
[05:41:52] [pool-2-thread-3/WARN]: Checksums do not match, retrying... client: 9376724cc233a3f5f7d5d127e6c3ee8e9b18b4016e1c898adaf73136f5f02482 server: a96d33cbcbc429a458e6d4472c14aa826f9f91e8a0b183e7c945f958c6157dab
[05:41:52] [pool-2-thread-4/WARN]: Checksums do not match, retrying... client: cd2e140e591c36a9dcef2e92a7d4864cc497fd9843d09fd0f0d5bb1d3abb699c server: 8d50898fac9cec9d83ea6e7329f7285aa370bf616f8666785a1a225052beb638
[05:41:52] [pool-2-thread-4/INFO]: Downloading worldedit.properties... (attempt 5)
[05:41:52] [pool-2-thread-3/INFO]: Downloading FabricHomes.properties... (attempt 5)
[05:41:52] [pool-2-thread-4/INFO]: URL: http://192.168.86.137:30037/config/worldedit/worldedit.properties
[05:41:52] [pool-2-thread-3/INFO]: URL: http://192.168.86.137:30037/config/FabricHomes.properties
[05:41:52] [pool-2-thread-4/WARN]: Checksums do not match, retrying... client: cd2e140e591c36a9dcef2e92a7d4864cc497fd9843d09fd0f0d5bb1d3abb699c server: 8d50898fac9cec9d83ea6e7329f7285aa370bf616f8666785a1a225052beb638
[05:41:52] [pool-2-thread-3/WARN]: Checksums do not match, retrying... client: 9376724cc233a3f5f7d5d127e6c3ee8e9b18b4016e1c898adaf73136f5f02482 server: a96d33cbcbc429a458e6d4472c14aa826f9f91e8a0b183e7c945f958c6157dab
[05:41:52] [pool-2-thread-4/ERROR]: Failed to download worldedit.properties after 5 attempts
[05:41:52] [pool-2-thread-3/ERROR]: Failed to download FabricHomes.properties after 5 attempts

**Comment by dAKirby309** [comment]
Server logs: 
[2023-02-04-6.log.gz](https://github.com/Skidamek/AutoModpack/files/10608598/2023-02-04-6.log.gz)
[2023-02-04-7.log.gz](https://github.com/Skidamek/AutoModpack/files/10608599/2023-02-04-7.log.gz)
[latest.log](https://github.com/Skidamek/AutoModpack/files/10608600/latest.log)

**Comment by Skidamek** [comment]
i mean these files worldedit.properties, FabricHomes.properties

**Comment by Skidamek** [comment]
or remove config from syncedFiles in config

**Comment by dAKirby309** [comment]
[FabricHomes and worldedit properties config files.zip](https://github.com/Skidamek/AutoModpack/files/10609099/FabricHomes.and.worldedit.properties.config.files.zip)

**Comment by Skidamek** [comment]
Actually i was debugging that a bit but i can't figure out why files like that returns wrong checksums...
At the moment one thing what _fixes_ it will be just excluding it from modpack

**Comment by dAKirby309** [comment]
I have excluded those two .properties files from the automodpack-server.json file, and the same thing happens. Is this not what you meant?

![image](https://user-images.githubusercontent.com/20955478/216779617-643677c5-b243-4447-a2a3-680a99aee03e.png)

**Comment by Skidamek** [comment]
Have you restarted the server?

**Comment by dAKirby309** [comment]
Yes, and I also tried deleting the automodpack folder from client after excluding those files.

**Comment by Skidamek** [comment]
Can you send client log? maybe some more file have some issues? Or just try removing config from `syncedFiles`

**Comment by dAKirby309** [comment]
Ok so I excluded the entire /config/ folder and then I was able to join the server (though it launched twice for some reason, and both Minecraft windows that opened are taking up like 1/5th of my screen for some reason, which is strange. But at least I was able to get on. 
![image](https://user-images.githubusercontent.com/20955478/216781605-c9c8db0d-90bf-4569-a910-fac05a4debea.png)

I will try to narrow down which config(s) are causing the issue, I suppose. Because apparently *something* in the /config/ folder was causing this issue of the client not properly working/connect. 

I did notice a strange behavior though, and that was all of the mods synced to .minecraft\automodpack\modpack\[IP]\mods but none of the mods went into my .minecraft\mods folder... and yet the client launched and loaded up all of the mods and I was able to connect to the server somehow. Are the mods being loaded from the automodpack folder instead of the native /mods/ folder somehow?
![image](https://user-images.githubusercontent.com/20955478/216781693-dfd298b6-ec72-4a2c-a27d-43f5ea2fe3b8.png)
![image](https://user-images.githubusercontent.com/20955478/216781733-143c1399-46e2-4c6a-814d-81f4657d4414.png)

**Comment by Skidamek** [comment]
Great. Weird issue with the screen didn't notice that yet. Two instances of the game likely are because automodpack re-launched game but you clicked launch button on launcher again.

> I did notice a strange behavior though, and that was all of the mods synced to .minecraft\automodpack\modpack[IP]\mods but none of the mods went into my .minecraft\mods folder... and yet the client launched and loaded up all of the mods and I was able to connect to the server somehow. Are the mods being loaded from the automodpack folder instead of the native /mods/ folder somehow?

Yeah exactly, it re-launches the game with special jvm property for fabric loader e.g. -Dfabric.addMods="pathToModsFolder" and so they are neatly segregated

**Comment by dAKirby309** [comment]
Ok so I tried reproducing the issue that I was having before where the client did not open after it downloaded the server's modpack and now it's loading up fine for some reason when it wasn't before.

I re-included the /config/ folder in the `syncedFiles` so now everything in /config/ syncs to the client (except for worldedit.properties and FabricHomes.properties) and deleted the Automodpack folder from my client like I tried before, but now things are working correctly somehow. Weird.

But now I am confused. Since mods are now instead loaded from the automodpack folder INSTEAD of from the .minecraft\mods folder, are the config files also loaded from the automodpack config folder INSTEAD of .minecraft\config too now? If so, I have some followup questions...

1) Where do I go now to edit configs? .minecraft\config, or automodpack\config? Are configs in .minecraft\config loaded up at all now?
2) How do we now go about installing and using client mods? I don't know where I'm supposed to put them to get them to load. I tried putting my client-side mods in .mincraft\mods and loaded up the game and got an error of many unmet dependencies. So that didn't work, unless I need the dependencies in .minecraft/mods AS WELL AS automodpack\mods to get the client mods to work?

I'm confused about how this 3.0.1 automodpack system works, as it seems very different from how it was in 2.4.1.

**Comment by Skidamek** [comment]
Ok, so as you noticed the system is very different than previous one.
 > Where do I go now to edit configs? .minecraft\config, or automodpack\config? Are configs in .minecraft\config loaded up at all now?

I tried making configs in automodpack folder work but that's just almost impossible, any different mod can handle their own configs in many different ways, so client can edit configs in `/.minecraft/config/`, not in any different automodpack folder at least if this config is marked as editable in modpack on server.

> How do we now go about installing and using client mods? I don't know where I'm supposed to put them to get them to load. I tried putting my client-side mods in .mincraft\mods and loaded up the game and got an error of many unmet dependencies. So that didn't work, unless I need the dependencies in .minecraft/mods AS WELL AS automodpack\mods to get the client mods to work?

Simply look at #93 I am close to fix this, so now you should simply place you own mods in normal `/.minecraft/mods/` folder without any issues in near future.

**Comment by dAKirby309** [comment]
I still don't quite understand. Where do we put the client mods if we want to keep them separate from the server-required mods? I tried putting them in the `host-modpack` folder as individual jars (along with the `modpack-content.json` but the game does not load again. I've tried going through this a few times and restarting the server, etc. 

Even when I delete the client mods that get put into my client's `automodpack\modpacks\[IP address]` folder and try launching the game, it does not open after I press Play.

I don't know why this is so complicated when it was so simple and worked effortlessly in the past. And I can't even get the 2.4.1 version to work anymore.

**Comment by Skidamek** [comment]
I am sorry this should be effortlessly as well but this is broken at the moment, got it working in dev today but need to fix few other things too. Tomorrow should be fix for that.

**Comment by dAKirby309** [comment]
Ok, thank you for the effort. I await the progress :)

**Comment by Skidamek** [comment]
Temporally fixed in 3.0.2, should be ok for time being. I will improve that in future
If you have any more questions just ask/reopen issue

**Comment by dAKirby309** [comment]
Did you make sure it worked with Fabric 1.19, because it doesn't work with it.

Server:
![image](https://user-images.githubusercontent.com/20955478/216830521-1162354f-c144-4847-afab-155268ae384e.png)

Client:
![image](https://user-images.githubusercontent.com/20955478/216830537-210f0a62-2d4f-48a8-8497-2b2ab61b5d1a.png)

**Comment by dAKirby309** [comment]
(Ignore my previous, deleted msg, I found a working version) Thanks for updating this! Initial testing shows that the client opens and works with 3.0.2. I'll mess around with it later today to see if it works out :)

**Comment by dAKirby309** [comment]
Yeah I don't know. It's still not working. This time I can't even download the modpack from the server.

First attempt using 3.0.2 connecting my client to the server:
It got stuck before anything was synced to my client.
![image](https://user-images.githubusercontent.com/20955478/216844869-f2a34aa8-57b0-42fe-848d-d23a74a1ae6e.png)
![image](https://user-images.githubusercontent.com/20955478/216844943-3f0dfa95-f51e-485c-b68d-cbf7153c8350.png)
Server: 
[2023-02-05-5.log.gz](https://github.com/Skidamek/AutoModpack/files/10613757/2023-02-05-5.log.gz)

Client: 
[2023-02-05-7.log.gz](https://github.com/Skidamek/AutoModpack/files/10613749/2023-02-05-7.log.gz)

Second attempt and logs:
It jumped up to 73/170 immediately and then stopped and did not progress.
![image](https://user-images.githubusercontent.com/20955478/216845075-70d5cb95-01cb-473e-b941-d7027dc7705d.png)
![image](https://user-images.githubusercontent.com/20955478/216845146-26d42949-fbfc-4a05-a998-4ccc08766fb0.png)
Server: 
[2023-02-05-6.log.gz](https://github.com/Skidamek/AutoModpack/files/10613755/2023-02-05-6.log.gz)
[latest.log](https://github.com/Skidamek/AutoModpack/files/10613756/latest.log)

Client: 
[latest.log](https://github.com/Skidamek/AutoModpack/files/10613750/latest.log)

**Comment by Skidamek** [comment]
Huh that's interesting, thanks for reporting though

**Comment by AStrong34** [comment]
@Skidamek Are you able to revert everything and go back to the last working version (v2.4.1) and test the new update for offline use on your end so we can continue using this cool mod until the update is ready without issues?

**Comment by Skidamek** [comment]
> @Skidamek Are you able to revert everything and go back to the last working version (v2.4.1) and test the new update for offline use on your end so we can continue using this cool mod until the update is ready without issues?

Sorry for that. You can use 2.4.1 but it have even more bugs. Releasing 3.0.3 in few mins should be ok

**Comment by Skidamek** [comment]
Please try 3.0.3 https://github.com/Skidamek/AutoModpack/releases/tag/v3.0.3

**Comment by dAKirby309** [comment]
Hi, I've been trying 3.0.3 and so it does download the mods, but I don't know why it's still not fully working. 

All the mods and configs get copied into the automodpack folder but the game doesn't open back up either on its own or when I manually try relaunching the game. It sits there working in the background (as evidenced by the `.minecraft\logs` folder files keep getting changed on their own, and after several minutes it sends an 'Uncaught exception in thread "main"` error for Fabric Loader.
![image](https://user-images.githubusercontent.com/20955478/217057197-c9940300-1392-40f5-ad54-c11c0498716d.png)

Here is a client-side log as it was doing stuff in the background: 
[send to dev latest.txt](https://github.com/Skidamek/AutoModpack/files/10668119/send.to.dev.latest.txt)

Additionally, I'm not sure if this is informative or not, but every time after I tried downloading the modpack from the server, it put these two mods into the `.minecraft\mods` folder - smoothchunk and hostile villages. Those two mods are also present in the `automodpack\..\mods` folder. 
![image](https://user-images.githubusercontent.com/20955478/217057912-363f1c6d-a400-4320-8417-19fa924dfb48.png)

I hope this helps.

**Comment by Skidamek** [comment]
Yhmm in logs it looks like you have many instances of minecraft opened in the same time...
Could you check task manager and kill every java related to minecraft task and try launching minecraft again?

**Comment by Skidamek** [comment]
this is strange

**Comment by Skidamek** [comment]
hostilevillages and smoothchunk shoudn't are forge mods, automodpack coudn't recognize that as a mod so copied it into the main minecraft folders

**Comment by Skidamek** [comment]
try removing hostilevillages and smoothchunk from modpack, that could potentially work...

**Comment by Skidamek** [comment]
I think i found the issue

**Comment by Skidamek** [comment]
Okay i have it, download correct fabric versions of hostilevillages and smoothchunk change them. Swap 3.0.3 build with this new i hope fixed now lol and try please it just must work now...

[new-build-unzip-this-file.zip](https://github.com/Skidamek/AutoModpack/files/10668501/new-build-unzip-this-file.zip)

**Comment by dAKirby309** [comment]
Ok, I haven't yet downloaded that new build you worked on, and I'm sorry if my comments don't suggest this, but I really appreciate your quick responses and the effort and care you're putting into this!

That aside, before I download that new build you just sent (thank you, btw), I must tell you that once I got the correct Fabric versions of hostile villages and smoothchunk, automodpack worked great and just like it should!

**Comment by Skidamek** [comment]
Great! Anyway if you could try this new build if it also works that good, this should even better but i am not too sure haha

**Comment by dAKirby309** [comment]
Hmm, well I replaced the other 3.0.3 file with this new build.zip and the mod was auto updated (to 3.0.3) on both client and server. But then when I tried to connect to the server to download the modpack, it said AutoModpack mismatch.

Updated to 3.0.3
![image](https://user-images.githubusercontent.com/20955478/217071577-93d60f88-2516-4b28-8f31-ead49bbdef60.png)

AutoModpack mismatch: 
![image](https://user-images.githubusercontent.com/20955478/217072063-6a182d41-b6a9-4771-b00b-51d1d3adbf88.png)

I have another potential concern for my use-case, but I'll send this info to you, above, first.

**Comment by Skidamek** [comment]
Oh u right, mod didn't build correctly lol
Now that is link from github actions this build should be correct https://github.com/Skidamek/AutoModpack/suites/10811957751/artifacts/543984796

**Comment by dAKirby309** [comment]
When trying that new build you sent (named artificats.zip), I got a critical error when trying to download the modpack. It seems to have stopped at the first mod in the list (alphabetical order), animal-feeding-trough. 
![image](https://user-images.githubusercontent.com/20955478/217088740-76685d5d-06c9-444e-b60c-4a6371761668.png)
Client log: 
[latest.log](https://github.com/Skidamek/AutoModpack/files/10669188/latest.log)

**Comment by Skidamek** [comment]
Hmm well that's ok i think for now 3.0.3 is good enough if someone doesn't have some files which shouldn't even be in modpack... Thank you so much! I will fix it next time probably with 3.0.4 release! :)
Have a good one!

**Comment by Skidamek** [comment]
Oh and button is below the error message progress XD

**Comment by dAKirby309** [comment]
Ok, I'll let you know if I encounter more issues. Seems like it's good now, but I had a niche concern but it seems to be working like it should for now so I won't bring it up unless I can prove it's a problem. Thanks for your work on this! It's an extremely useful mod you've made! <3

**Comment by dAKirby309** [comment]
I know that personally, I would refer being able to use 2.4.1 instead of 3.0.x version 3 is polished and extensively tested, since 2.4.1 never gave me any trouble and now I'm not able to use it anymore.

I know I said that 3.0.3 was working for me, but I know someone that it is not working for and they're having issues with it. And after some more testing, it seems I may also be having an issue with it, where it doesn't seem to work potentially with .minecraft folders that are in another location, and are in %appdata% via a symbolic link. When I tried my Minecraft folder that was a symbolic link, the game didn't want to launch after downloading the modpack from the server. 

I know you mentioned that you say 2.4.1 has several bugs. Though my friend and I haven't encountered a single issue with it and all the time we used it.

Is there any way that this 3.0.3 mod can be considered a beta, and somehow get 2.4.1 working again? I think this mod is great and super useful, but I just don't feel it is polished and ready enough to be the version everyone has to use, before it gets polished.

**Comment by oakelope** [comment]
If you look threw the thread there is this version that works mostly just make sure to disable the update modpack button in the config because I forgot to disable that from updating the mod 

https://github.com/Skidamek/AutoModpack/issues/92#issuecomment-1415115112

**Comment by dAKirby309** [comment]
> If you look threw the thread there is this version that works mostly just make sure to disable the update modpack button in the config because I forgot to disable that from updating the mod
> 
> [#92 (comment)](https://github.com/Skidamek/AutoModpack/issues/92#issuecomment-1415115112)

Here's the issue with that,
![image](https://user-images.githubusercontent.com/20955478/217141211-a22557ce-954d-4aa7-9729-14ce8fccec72.png)
And I also get this sort of error 
![image](https://user-images.githubusercontent.com/20955478/216762940-397c09aa-914c-4a41-8715-ef21df824301.png)

I've not been able to figure that out. It didn't happened back before 2.4.1 received a `disabled auto update` change made to it.
[latest.log](https://github.com/Skidamek/AutoModpack/files/10671328/latest.log)

**Comment by dAKirby309** [comment]
I have realized that the `Connection Lost` error that I am now getting on 2.4.1 (without auto update) must be due to some mod-related issue on my end. I tried testing 2.4.1 with a small number of mods instead of all of our mods, and it works. So I'll try spending time tomorrow troubleshooting that.

**Comment by Skidamek** [comment]
> > > @Skidamek Are you able to revert everything and go back to the last working version (v2.4.1) and test the new update for offline use on your end so we can continue using this cool mod until the update is ready without issues?
> > 
> > Sorry for that. You can use 2.4.1(.0) but it have even more bugs. Releasing 3.0.3 in few mins should be ok
> 
> So does version 2.4.1 work again? I know when you first made changes to not have it auto update when using 2.4.1 it would not work correctly. Currently having a ton of issue trying to get version 3.0.3 to work and would like if you just reverted every single update and go back to that last known working version (v2.4.1) and to not update this mod anymore as there were no issues we encountered when using it and did everything correctly! Thank you!
> 

So strange that you didn't have any bugs i thought everyone having many troubles because of number of known issues, so with this knowledge someone for sure doesn't have also any trouble with 3.0.3 lmao

But yes you can without problem download 2.4.1.0 version from modrinth it works the same as previous 2.4.1 but it is without auto updating. However if you could describe your problem that's would be win-win right?

**Comment by Killasaurus-Warbear** [comment]
I'm having the auto-restart loop issue with 3.0.3. Not sure if I should start a new issue or not, but I haven't been able to make any progress resolving it. Any new information?

**Comment by Skidamek** [comment]
> I'm having the auto-restart loop issue with 3.0.3. Not sure if I should start a new issue or not, but I haven't been able to make any progress resolving it. Any new information?

Start new issue and send there two latest logs from client please

**Comment by Skidamek** [comment]
Ok guys i was thinking about that and i made a decision to remove relauncher and copy mods to main minecraft folder kinda like it was before what do you think about that? This segregation to folders and auto relauncher is cool but due to many issues you having i think would be better to change that, no?

**Comment by dAKirby309** [comment]
Is that is the main cause of the issues that people are having, then that may be for the best. I like the ideas that you have made it happen for version 3+, But I have found the older versions to be a lot more reliable. I was able to get version 2.4.1 working, and I found the culprit. It was another mod that wasn’t properly supported by 1.19 Fabric. 

But I do like some of the changes in version 3+ such as auto restarting the game. It didn't work often, but I did get it to work a couple times which was nice.

**Comment by Eianex** [comment]
Hi @Skidamek, I appreciate your active involvement with the community. I'm encountering the same issue as the original poster with the error message:

"Uncaught exception in thread "main"
java.lang.RuntimeException: Error creating Mixin config nochatreports.mixins.json for mod nochatreports
at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:95)
at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:153)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config nochatreports.mixins.json
at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:93)
... 3 more
Caused by: java.lang.IllegalArgumentException: The specified resource 'nochatreports.mixins.json' was invalid or could not be read
at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1290)
at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
... 6 more"

I am using version 3.0.3 of the Automodpack. Previously, I was using version 2.4.1, and it worked without any issues. I love the new progress bar animation during downloads, but I have been facing several errors, and it has been challenging for me as a server admin. I would like to have the simplicity of the previous version along with the beauty of the current version of this mod.

I am also experiencing this error message:

"Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.lambda$discoverMods$1(ModDiscoverer.java:146)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:146)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:210)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 3 more
	Suppressed: java.lang.RuntimeException: java.lang.RuntimeException: Error analyzing [C:\Users\atama\AppData\Roaming\.minecraft\automodpack\modpacks\91.134.125.156-8045\mods\NoChatReports-FABRIC-1.19.2-v1.13.0.jar]: java.util.zip.ZipException: zip END header not found
		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
		at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
		at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562)
		at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:604)
		at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:981)
		at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:143)
		... 5 more
	Caused by: java.lang.RuntimeException: Error analyzing [C:\Users\atama\AppData\Roaming\.minecraft\automodpack\modpacks\91.134.125.156-8045\mods\NoChatReports-FABRIC-1.19.2-v1.13.0.jar]: java.util.zip.ZipException: zip END header not found
		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:263)
		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:212)
		at java.base/java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100)
		at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
		at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
		at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
		at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
		at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
	Caused by: java.util.zip.ZipException: zip END header not found
		at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
		at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
		at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
		at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
		at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
		at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
		at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
		at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:284)
		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:253)
		... 7 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Error analyzing [C:\Users\atama\AppData\Roaming\.minecraft\automodpack\modpacks\91.134.125.156-8045\mods\fabric-api-0.63.0+1.19.2.jar]: java.util.zip.ZipException: zip END header not found
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562)
	at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:604)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:981)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:143)
	... 5 more
Caused by: java.lang.RuntimeException: Error analyzing [C:\Users\atama\AppData\Roaming\.minecraft\automodpack\modpacks\91.134.125.156-8045\mods\fabric-api-0.63.0+1.19.2.jar]: java.util.zip.ZipException: zip END header not found
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:263)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:212)
	at java.base/java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:284)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:253)
	... 7 more"

**Comment by Eianex** [comment]
Postdata:

1. I was using 3 mods: 

- fabric-api-0.63.0+1.19.2
- NoChatReports-FABRIC-1.19.2-v1.13.0
- automodpack-3.0.3-1.19.2

and it did autoinstalled me this one:

- adaptive_performance_tweaks_1.19.2-6.4.0

2. I loved the possibility as a server admin to being able to separate client-side mods and server-sided ones. Thanks for all!

**Comment by Skidamek** [comment]
Thanks, working on it, at the moment you can still use old 2.4.1.0 (updated from e.g. modrinth) if that was not a problem

**Comment by Skidamek** [comment]
Fixed in 3.1.0 beta (only 1.19.2 at the moment)
